apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: web-api
  namespace: mta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - image: hienvannguyen/web-api:1.0
        name: web-api
        ports:
          - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  type: NodePort
  selector:
    app: web-api
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 31000