
# kubectl delete rs redis-rs rediscommander-rs mongo-rs -n mta
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-rs
  namespace: mta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-dev
  template:
    metadata:
      labels:
        app: redis-dev
    spec:
      containers:
      - image: redis
        name: redis-container
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis-dev
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-rs
  namespace: mta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-dev
  template:
    metadata:
      labels:
        app: mongo-dev
    spec:
      containers:
      - image: mongo
        name: mongo-container
        ports:
          - containerPort: 27017
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo-dev
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rediscommander-rs
  namespace: mta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rediscommander-dev
  template:
    metadata:
      labels:
        app: rediscommander-dev
    spec:
      containers:
      - image: rediscommander/redis-commander
        name: rediscommander-container
        ports:
          - containerPort: 80
            protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: rediscommander-service
spec:
  type: NodePort
  selector:
    app: rediscommander-dev
  ports:
  - port: 80
    targetPort: 8081
    nodePort: 32000